server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    url: jdbc:mysql://localhost:3307/cloud2020?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yuxiang.springcloud.entities #所有entity别名所在包

management:
  endpoints:
    web:
      exposure:
        include: '*'