server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    url: jdbc:mysql://localhost:3307/cloud2020?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456

eureka:
  client:
    #表示是否将自己注册金eurekaserver 默认为true
    register-with-eureka: true
    #是否从eureka抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yuxiang.springcloud.entities #所有entity别名所在包