server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbit mq的服务信息
        defaultRabbit: # 表示定义的名称，用于binding整合
          type: rabbit # 消息组件类型
          environment: #设置rabbit mq的相关的环境配置
            spring:
              rabbitmq:
                host: 192.168.67.132
                port: 5672
                username: guest
                password: guest
      bindings: #服务的整合处理
        input : #通道名称
          destination: studyExchange #表示要使用的exchangem名称定义 跟消息提供者保持一致
          content-type: application/json #设置消息类型可以为json，文本为：text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: cloud-stream-consumer #分组，同一个组中的消费者竞争消息，避免消息重复消费；不同组中的可以重复消费


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳时间间隔 默认30S
    lease-expiration-duration-in-seconds: 5 #如果现在超过了5s的间隔 默认90S
    instance-id: send-8802.com #在信息列表时显示主机名称
    prefer-ip-address: true # 访问的路径变为ip地址

