server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery: #Nacos注册中心地址
        server-addr: localhost:8848
    alibaba:
      seata:
        # 自定义事务组的名称需要与seata-server中一致
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    url: jdbc:mysql://localhost:3307/cloud2020?useUnicode=yes&characterEncoding=UTF8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
    username: root
    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
feign:
  hystrix:
    enabled: true

logging:
  level:
    io:
      seata: info
mybatis:
  mapper-locations: classpath:mapper/*.xml